language: python
python:
- '3.8'
services:
- postgresql
install:
- pip install pipenv
- pipenv install
before_script:
- psql -c 'CREATE DATABASE eth_crowdfund_api_db_test;' -U postgres
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: rAyQ5QJKwO75xyAPWo3+7Nt0f//I1XEZRJ/9bek4tBOguzOzjJJRT+3zYXfndi1nPusttGM4wMzyssJYLFMjo64vazABNg/7/pB3Da0Fp8J9SLfkkwSFRROSdm9x72hyIuPyyhu3XStw0VOFCv3miEzOn2fOCf9b9Rw5+MX7EUI+PKuSbNUTJ/4Rn/qkTukQl5z57Achte26I/OVt1M68Bex3MZjI4vcAZzR6XgBtzUcZmtZffS5TLNUcxEQ+3qMl9TBT0OzOZi3bL9oBKLCrdF5s97x32Fs3ZORojw7sppozLQx9fGmCKtKGfxLES6SQ3rCWctYATH9Jyxu9ypWOzPAh1nfY8iKffwk3ojtGZjgq/03GVcbuwRhDsU9PTRiLfZUMA/blcTw7oYHmpRUHsXqQy/LMxHItNuLQzVLpGbWMz9ejyWzn45uroW8m4Jd4wUO7PnW+ZJYA9xaYO/SgeLBXhA5bJgcAdK4rXbFtOLz041VfTEzQoKglocjE6T8XoZWYyhM3zG6TlXV5D2Rzhlc5XdCxhWqaX2Wn5izalO8OhXLA+zoWs/hEtf8C9X+rYR5aFnfYubFtzp0XJOJhPtaFvsIhm3Noqrvy2Q3+gdC06Q3tAi32hNntRrOgjnDLAwDbaqdPq1gweQ3GLLs0xqpA/QQf+Ruo4iuZwfq8Gg=
  app: etho-boost
  run: pipenv shell
  run: python manage.py db stamp head
  run: python manage.py db migrate
  run: python manage.py db upgrade
  skip_cleanup: 'true'
