language: python
python: 
  - "3.8.5"
addons:
  postgresql: "12.3"
services:
  - postgresql
install:
  - pip install -r requirements.txt
script:
  - pipenv install flask_script
  - python manage.py db migrate
  - python manage.py db upgrade
deploy:
  provider: heroku
  api_key:
    secure: FE6USvgsV83Ub+AIQNLn86gQ8B05Zt0PA9Pobx8be2lDPYphiqNYStHns2H/1+vCvkhsPftgQaXBWHmMbqTbRpKoaKN9FcHNOxGldwSVuIITEYItspEqyWp8d2+JTOHuGTY3B9X25xK1uB86OwQsRu5GBCdav5ztf9mJmHug3mnmbEA73IHQ6ZMThWeFhClANhgnT0qr5Ua3iBeWz7D9rUhaYmD8BAdAuaztq40FBpR7BKWW91xypk2DbWD4mR47U8WxMJyQSw70Hkm/HU89YdAIIp4jqlpRhpAYXK8QwGXX8ecvCazKoAE9NzWfVFYddc+XWzUrzE+u3z7PePiq8hRPGCWknA9UlNKY9XMdPDlKAdCeTNqBmCwyXWZLxbWkD56C8WFD9zlQHLTXyzpzPM8E7y0CFFkz9LOQaZhl9/ipeqn25m62ikOF2Q5I9buqyHg7KjNgCvM7VjW1vGWczsKoRtZaV1UCKjcgTfhnionHosDrRa34sGkOgdmVFke04YsnbEsAkFYeweO/tNdQ388/ygIj3UVwy4C7L0DM0ktdRBjRNX6NsTqhE7IXa3LC1HW4hTw/fygLnJ8qaTggQf+5FAHPQLvZdKG6UxFy89+zpLo+YcUUzylar/SHS7D4mEe+xlY+OEPps587soLXgR+1NYJjJK1J1QXsWjKWiM0=
  app: etho-boost
  on:
    repo: Eth-Crowdfund/eth_crowdfund_be
