language: python
python:
  - "3.8"
services:
  - postgresql
adons: 
  postgresql: "12.3"
install:
  - pip install pipenv
  - pipenv install
before_script: 
  - psql -c 'CREATE DATABASE eth_crowdfund_api_db_test;'
script:
  - pytest
deploy:
  provider: heroku
  api_key:
    secure: FXyiqE3KUUtbGTOQDEBoQrY3dL4PCv1zNSYkv5KFCoKxUJOWwYfqrIPwPoFeAGliu4LxJImBnEvWEehfAFep2H/+A0fGewtTpKX7GJtl9h+rIOGfq/ipX4KeFR4LIrC8g14ebfdxls29l3dg5bLuWEJCTI4ZaFfZZmNI/6mjs3VNOZHCoOnzURZH1dgTGfRWT4pwuZZ9gh477CcG5iKuoGoXKSXXfke+XaZ1Fa4Xl5aiqRyJdHrJMh1qgt/HvjAXfWTZdqI5oh+St85irjiOqM6H2wtMqFNoqlaSBS+jYZpN7r6Byj/nMElmP35JQ97jdBVYSjD4hu4V+1G5XctpgAhIryKV4/w3bwhaAM4axLx58cDh1p/M/bYMV/sx4bEWiYgQ79tdHf9Yiyx/pCWeOLuDd6Q5u/ZHIardrhyayqchoS/wkr5DxRo1v40dWjGHs6AFOSO8eALq4iqbXPU1U6ZpL9Gw5t2D7FSdG4jaEhdyI7kU1NVTgXR8aRtKaBqbI3u0C4qW2eE9OcLP7MWyQebASFA2/RZA6YB8NvLHlZiR89hWf+B75gyDYwVuvcet6zCRncxv0FoW6uqod2je0Aa0ZijZvV2FHK2lTE09ULhAQwWA9VkjYfcPJtZAKpLJHtsYGlQDzETAMLT9jLZYQQYqkpmPYe6y8gJJHy2lJ30=
  app: etho-boost
  on:
    repo: Eth-Crowdfund/eth_crowdfund_be