language: python
python:
- '3.8'
services:
- postgresql
install:
- pip install pipenv
- pipenv install
before_script:
- psql -c 'CREATE DATABASE eth_crowdfund_api_db_test;' -U postgres
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: cKtlwWdWMob1rIr9bwBSfFUXGcqDbTUKSa97vF5B1J5wLNv2SMcjs57Bfq3SVkXEKv98+C+Ps7k8oGdQzHSsaOJ6lLbQG/TLbslY+G60P6IrNtmEu4qBWfDxL8WdWMXGLAXqn+Gr+lk3SyhuRxMBuoI1t5j3G5+eqmJWAdjB9S122WxznC7F7vzQyGGctV7Vmz5Fr0pKVRDUacIUtSu854QP384JRlncIU0MScLhiFE5ifnct/kZ0NzaF9N1f83lKgqExWBAHf49Y4UvKwdB7Yk+L9dvsQO7V8L0fWz0MP+9LVvD1tb7SOb1HjD4dLMW6GoY8ZW2HSioGzNwCRjH7Hq8cm12hUcY+PyCXGIXixeEOiebVaQjijE0eXJXIgEE5u171f71jo9/+sDLzLe9uGSb6VTe87A76gS13y9BjF0ngrUaHnYIuniblS4y9FTEjo32RlkR9OKIry48gqAuC46vL5OggKJjcMdnHf5RcBve5jD5evBnlDZLTi5YTeS4mCIBYgx7nt1PXqNN0+/XbOXwJ3/g2NuDRIDIWZAWtlMsbQkxB/6LLeIFMFp9LkMHNX3Udnn7eNladGjLV0ZiikIvMuYgnlOKUfu41pn2moRsvXzRKncoys1O/dAUV3I/OVtnOiBMX+XGtzilJpvW41xUVbpZBXKRNMlyXnWw8D4=
  app: etho-boost
  run: pipenv shell
  run: python manage.py db stamp head
  run: python manage.py db migrate
  run: python manage.py db upgrade
  skip_cleanup: 'true'
